[package]
name = "macroquad-translucency"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "translucency"
path = "src/translucency.rs"

[[bin]]
name = "well"
path = "src/well.rs"

[dependencies]
macroquad = "0.4.13"
